name: Sync Fork with Upstream

on:
  schedule:
    # This will run every 15 minutes
    - cron: '*/15 * * * *'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the fork repository
        uses: actions/checkout@v2
        with:
          repository: ZackTheGrumpy/ManifestInTesting
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Add upstream remote
        run: git remote add upstream https://github.com/xu654/Manifest.git

      - name: Fetch upstream changes
        run: |
          for i in {1..5}; do
            git fetch --verbose upstream --depth=10 && break || sleep 15;
          done

      - name: Merge upstream changes into fork
        run: git merge upstream/main --allow-unrelated-histories

      - name: Push changes to your fork
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
